"""Fail-closed global and account-level new-order controls."""

from .contracts import (
    KILL_SWITCH_ENGINE_VERSION,
    KillSwitchActivationRequest,
    KillSwitchActor,
    KillSwitchActorKind,
    KillSwitchActorRole,
    KillSwitchAuditEvent,
    KillSwitchEventType,
    KillSwitchGateDecision,
    KillSwitchGateReason,
    KillSwitchGateRequest,
    KillSwitchGateStatus,
    KillSwitchIncident,
    KillSwitchRecoveryApproval,
    KillSwitchRecoveryRequest,
    KillSwitchScope,
    KillSwitchState,
    KillSwitchStatus,
    KillSwitchTransition,
    KillSwitchTriggerSource,
)
from .repository import (
    InMemoryKillSwitchRepository,
    KillSwitchAuthorizationError,
    KillSwitchConcurrentUpdate,
    KillSwitchIdempotencyConflict,
    KillSwitchIncidentConflict,
    KillSwitchIncidentNotFound,
    KillSwitchRepository,
    KillSwitchRepositoryConflict,
    KillSwitchRepositoryError,
    KillSwitchStateNotFound,
)
from .service import (
    KillSwitchOrderBlocked,
    KillSwitchRecoveryAuthorizer,
    KillSwitchService,
)
from .sqlite_repository import SQLiteKillSwitchRepository

__all__ = [
    "KILL_SWITCH_ENGINE_VERSION",
    "InMemoryKillSwitchRepository",
    "KillSwitchActivationRequest",
    "KillSwitchActor",
    "KillSwitchActorKind",
    "KillSwitchActorRole",
    "KillSwitchAuditEvent",
    "KillSwitchAuthorizationError",
    "KillSwitchConcurrentUpdate",
    "KillSwitchEventType",
    "KillSwitchGateDecision",
    "KillSwitchGateReason",
    "KillSwitchGateRequest",
    "KillSwitchGateStatus",
    "KillSwitchIdempotencyConflict",
    "KillSwitchIncident",
    "KillSwitchIncidentConflict",
    "KillSwitchIncidentNotFound",
    "KillSwitchOrderBlocked",
    "KillSwitchRecoveryApproval",
    "KillSwitchRecoveryAuthorizer",
    "KillSwitchRecoveryRequest",
    "KillSwitchRepository",
    "KillSwitchRepositoryConflict",
    "KillSwitchRepositoryError",
    "KillSwitchScope",
    "KillSwitchService",
    "KillSwitchState",
    "KillSwitchStateNotFound",
    "KillSwitchStatus",
    "KillSwitchTransition",
    "KillSwitchTriggerSource",
    "SQLiteKillSwitchRepository",
]
